[project]
name = "muscle-man"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.4",
    "jinja2-fragments>=1.6.0",
    "pydantic-settings>=2.6.0",
    "sqlmodel>=0.0.22",
    "uvicorn>=0.32.0",
]
